name: NodeaaS Release Workflow
on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2.3.4
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - id: build
        name: Build
        run: |
          npm ci
          npm run build
      - id: npm_publish
        name: Publish
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
